version: "3.3"
services:
  web:
    build: .
#      context: ./app
#      dockerfile: Dockerfile
    ports:
      - "8888:5000"
    volumes:
      - .:/code
    environment:
      FLASK_ENV: development
  redis:
    image: "redis:alpine"
  pytest:
    build: 
      context: ./pytest 
      dockerfile: Dockerfile
    depends_on:
      - web
      - redis
